# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7esIUncjaruPbZ8OaIu-oDnDaJyjyo2
"""

print("Enter initial state (use X, O and -):")
board = input().split()
def display():
    print()
    print(board[0], "|", board[1], "|", board[2])
    print("---------")
    print(board[3], "|", board[4], "|", board[5])
    print("---------")
    print(board[6], "|", board[7], "|", board[8])
    print()
def winner():
    win = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]
    for a, b, c in win:
        if board[a] != '-' and \
           board[a] == board[b] == board[c]:
            return board[a]
    return None
def full():
    return '-' not in board
def ai_move():
    for i in range(9):
        if board[i] == '-':
            board[i] = 'O'
            if winner() == 'O':
                return
            board[i] = '-'
    for i in range(9):
        if board[i] == '-':
            board[i] = 'X'
            if winner() == 'X':
                board[i] = 'O'
                return
            board[i] = '-'
    if board[4] == '-':
        board[4] = 'O'
        return
    for i in range(9):
        if board[i] == '-':
            board[i] = 'O'
            return
cost = 0
print("\nInitial State:")
display()
while True:
    print("Your turn (X)")
    cell = int(input("Enter cell number (1-9): "))
    if cell < 1 or cell > 9:
        print("Invalid cell!")
        continue
    if board[cell - 1] != '-':
        print("Cell already occupied!")
        continue
    board[cell - 1] = 'X'
    cost = cost + 1
    print("\nAfter your move:")
    display()
    if winner() == 'X':
        print("You win!")
        print("Path Cost:", cost)
        break
    if full():
        print("Game Draw!")
        print("Path Cost:", cost)
        break
    print("AI is thinking...")
    ai_move()
    cost = cost + 1
    print("\nAfter AI move:")
    display()
    if winner() == 'O':
        print("AI wins!")
        print("Path Cost:", cost)
        break
    if full():
        print("Game Draw!")
        print("Path Cost:", cost)
        break